name: CI
on: [ pull_request ]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
        poetry-version: [ "1.2.2" ]
        os: [ ubuntu-22.04, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install poetry project (and dependency)
        run: poetry install
      - name: Test poetry project
        run: poetry run pytest
